#!/bin/bash

echo "🚀 GitHub Push Helper"
echo "===================="
echo ""
echo "This script will help you push the code to your GitHub repository."
echo ""
echo "You have a few options:"
echo ""
echo "Option 1: Using GitHub CLI (recommended)"
echo "-----------------------------------------"
echo "If you have GitHub CLI installed, run:"
echo "  gh auth login"
echo "  git push -u origin main"
echo ""
echo "Option 2: Using Personal Access Token"
echo "--------------------------------------"
echo "1. Create a token at: https://github.com/settings/tokens"
echo "2. Run: git push https://YOUR_TOKEN@github.com/mgavrish-dm/hackathon-group-4.git main"
echo ""
echo "Option 3: Using SSH"
echo "-------------------"
echo "1. Set up SSH keys: https://docs.github.com/en/authentication/connecting-to-github-with-ssh"
echo "2. Change remote to SSH:"
echo "   git remote set-url origin git@github.com:mgavrish-dm/hackathon-group-4.git"
echo "3. Run: git push -u origin main"
echo ""
echo "Option 4: Manual push with username/password"
echo "--------------------------------------------"
echo "Run the following command and enter your GitHub credentials:"
echo "  git push -u origin main"
echo ""
echo "Current repository status:"
git status --short
echo ""
echo "Remote repository:"
git remote -v
echo ""
echo "To view your repository after pushing:"
echo "https://github.com/mgavrish-dm/hackathon-group-4"
